name: gsheet
description: A new Flutter application.
publish_to: 'none'
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  gsheets: ^0.4.2
#  googleapis: ^8.0.0
#  googleapis_auth: ^1.3.0
#  http: ^0.13.0
#  meta: ^1.3.0
#  collection: ^1.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true